### ISSUE TITLE
KeyError '_password_policies_change_required'

### ISSUE THREAD

**Issue by xusy2k** [tarak/django-password-policies#31]
If I set PASSWORD_USE_HISTORY to False I always get this exception

**Comment by tarak** [comment]
Can you provide the whole stack trace?

**Comment by xusy2k** [comment]
Environment:


Request Method: GET
Request URL: http://localhost:8000/admin/

Django Version: 1.5.12
Python Version: 2.7.6
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.admin',
 'django.contrib.admindocs',
 'password_policies')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'password_policies.middleware.PasswordChangeMiddleware')


Traceback:
File "/home/xus/.virtualenvs/test_django/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  90.                     response = middleware_method(request)
File "/home/xus/.virtualenvs/test_django/local/lib/python2.7/site-packages/password_policies/middleware.py" in process_request
  149.             return self._redirect(request)
File "/home/xus/.virtualenvs/test_django/local/lib/python2.7/site-packages/password_policies/middleware.py" in _redirect
  125.         if request.session[self.required]:
File "/home/xus/.virtualenvs/test_django/local/lib/python2.7/site-packages/django/contrib/sessions/backends/base.py" in __getitem__
  44.         return self._session[key]

Exception Type: KeyError at /admin/
Exception Value: '_password_policies_change_required'

**Comment by tarak** [comment]
Thx! Can you try to remove the 'password_policies.middleware.PasswordChangeMiddleware'. Won't work anyway if you set PASSWORD_USE_HISTORY to false I think...

The middleware is not very reliable and needs to be rewritten.

Is there a reason why you need the middleware and disable the usage of the password history at the same time?

**Comment by xusy2k** [comment]
Thx! It worked!
Only reason for need the middleware and disable the usage of the password history is for testing PASSWORD_CHECK_ONLY_AT_LOGIN = False feature, but I don't want to use historic passwords.
Finally I set PASSWORD_HISTORY_COUNT = 1

**Comment by tarak** [comment]
So this issue could be closed?

**Comment by xusy2k** [comment]
Yes!, It worked for me

**Comment by tarak** [comment]
Closing as it seems to work for @xusy2k.
