### ISSUE TITLE
Create password history when commit = True

### ISSUE THREAD

**Issue by HuskerBob** [tarak/django-password-policies#43]
I propose that the creation of a PasswordHistory record should only occur when the 'commit' parameter is True. This allows a sub-form to make the call  object = form.save(commit=False) to get the user object without creating a history record.

File: forms/__init__.py 
class PasswordPoliciesForm
method save()
Code: Indent lines 95 to 99.

**Comment by tarak** [comment]
Ok. Have you tried to run the tests with the change you are proposing and would it be necessary to add more testing? A PR is always appreciated...

**Comment by HuskerBob** [comment]
I am working on testing the change.
