### ISSUE TITLE
Is the pytz dependency still current?

### ISSUE THREAD

**Issue by mhogg** [tarak/django-password-policies#47]
From what I can see, the pytz package is no longer used. Rather, django.utils.timezone appears to be used instead. Is pytz still required?

**Comment by tarak** [comment]
Probably not. I don't have access to my personal workstation to grep inside the code. If you have verified that the module is not used anymore I would gladly merge a PR.

**Comment by citmusa** [comment]
I've just installed the 0.4.2 version, and I can confirm that you have to install pytz.
(I've got an error from django until I installed pytz manually)

Using:
- Django==1.9.10, PasswordChangeMiddleware, context_processors.password_status
