### ISSUE TITLE
get_current_site() will no longer be importable from django.contrib.sites.models

### ISSUE THREAD

**Issue by setsu** [tarak/django-password-policies#50]
Hi
with django 1.9, an error occured when setting-up the application.

  File "XXX/lib/python3.5/site-packages/password_policies/urls.py", line 3, in <module>
    from password_policies.views import PasswordChangeFormView
  File "XXX/lib/python3.5/site-packages/password_policies/views.py", line 19, in <module>
    from password_policies.forms import PasswordPoliciesForm
  File "XXX/lib/python3.5/site-packages/password_policies/forms/__init__.py", line 8, in <module>
    from django.contrib.sites.models import get_current_site
ImportError: cannot import name 'get_current_site

In Django Deprecation Timeline
https://docs.djangoproject.com/es/1.9/internals/deprecation/#deprecation-removed-in-1-9
there is the reason
"**RequestSite and get_current_site() will no longer be importable from django.contrib.sites.models.**"

Is it possibile to fix it with 

```
try:
    from django.contrib.sites.models import get_current_site
except ImportError:
    from django.contrib.sites.shortcuts import get_current_site
```

, correct?

Thank you
Pietro

**Comment by brianmay** [comment]
Django 1.9 was released December last year. Django 1.10 will be released in August. Any chance for a fix for this?

**Comment by brianmay** [comment]
Looks like this was fixed in #49 (November 2015) - the fact nobody has responded to this ticket or made a new release would suggest this project is dead.

**Comment by tarak** [comment]
Nope. Not dead. Just on a very much needed holiday. Will take care of
things next week when I get home...

**Comment by andrijan** [comment]
Any news on this reaching pypi?
